# Generated by Django 3.0.7 on 2020-07-10 17:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasktracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='template_counter',
        ),
        migrations.RemoveField(
            model_name='task',
            name='template_intervals',
        ),
        migrations.AlterField(
            model_name='task',
            name='lost_time',
            field=models.TimeField(default='17:39'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_begin',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 10, 17, 39, 22, 860976)),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_end',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 10, 17, 39, 22, 860998)),
        ),
    ]
