# Generated by Django 3.0.7 on 2020-07-10 17:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tasktracker', '0003_auto_20200710_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_begin',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 10, 17, 44, 27, 136801, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_end',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 10, 17, 44, 27, 136825, tzinfo=utc)),
        ),
    ]
