# Generated by Django 3.0.7 on 2020-07-10 17:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tasktracker', '0005_auto_20200710_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='template_counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='template_intervals',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='lost_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_begin',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 10, 17, 59, 15, 522065, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_end',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 10, 17, 59, 15, 522090, tzinfo=utc)),
        ),
    ]
