# Generated by Django 3.0.7 on 2020-07-13 21:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tasktracker', '0006_auto_20200710_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_state',
            field=models.CharField(choices=[('I', 'Idle'), ('A', 'Active'), ('P', 'Paused')], default='I', max_length=1),
        ),
        migrations.AddField(
            model_name='task',
            name='task_statistic',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_begin',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 13, 21, 19, 27, 61616, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_end',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 13, 21, 19, 27, 61641, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='traking_type',
            field=models.CharField(choices=[('U', 'Untracked'), ('F', 'Fixed'), ('P', 'Period')], default='U', max_length=1),
        ),
    ]
