# Generated by Django 3.0.7 on 2020-07-13 21:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasktracker', '0007_auto_20200713_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_begin',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 13, 21, 21, 26, 725624)),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_end',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 13, 21, 21, 26, 725649)),
        ),
    ]
