# Generated by Django 3.0.7 on 2020-07-21 06:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasktracker', '0010_auto_20200721_0614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='active_intervals',
            field=models.CharField(db_index=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_begin',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 21, 6, 15, 17, 560934)),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_end',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 21, 6, 15, 17, 561027)),
        ),
    ]
