# Generated by Django 3.0.7 on 2020-07-21 06:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasktracker', '0011_auto_20200721_0615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='active_intervals',
        ),
        migrations.AlterField(
            model_name='task',
            name='task_begin',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 21, 6, 18, 55, 368464)),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_end',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 21, 6, 18, 55, 368527)),
        ),
    ]
