# Generated by Django 3.0.7 on 2020-07-21 06:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasktracker', '0012_auto_20200721_0618'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='active_intervals',
            field=models.CharField(db_index=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_begin',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 21, 6, 19, 35, 458093)),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_end',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 21, 6, 19, 35, 458229)),
        ),
    ]
