# Generated by Django 3.0.7 on 2020-07-23 12:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasktracker', '0013_auto_20200721_0619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_begin',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 23, 12, 36, 48, 782623)),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_end',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 23, 12, 36, 48, 782675)),
        ),
    ]
