# Generated by Django 3.0.7 on 2020-07-24 13:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasktracker', '0014_auto_20200723_1236'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_point', models.DateField(default=datetime.datetime(2020, 7, 24, 13, 21, 0, 167953))),
                ('task_in_point', models.IntegerField(default=0)),
                ('task_complited', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='task',
            name='active_intervals',
        ),
        migrations.RemoveField(
            model_name='task',
            name='exclude_selected',
        ),
        migrations.RemoveField(
            model_name='task',
            name='task_statistic',
        ),
        migrations.RemoveField(
            model_name='task',
            name='template_counter',
        ),
        migrations.RemoveField(
            model_name='task',
            name='template_task',
        ),
        migrations.AddField(
            model_name='task',
            name='template_of',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templ_of', to='tasktracker.Task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_begin',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 24, 13, 21, 0, 165347)),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_end',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 24, 13, 21, 0, 165402)),
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_intervals', models.CharField(db_index=True, default='', max_length=32)),
                ('exclude_selected', models.BooleanField(default=False)),
                ('template_counter', models.IntegerField(default=0)),
                ('template_statistic', models.IntegerField(default=0)),
                ('template_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templ_to', to='tasktracker.Task')),
            ],
        ),
    ]
