# Generated by Django 3.0.7 on 2020-07-24 13:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasktracker', '0015_auto_20200724_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='is_habit',
        ),
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('S', 'Simple'), ('T', 'Template'), ('D', 'Decomposite')], default='S', max_length=1),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='date_point',
            field=models.DateField(default=datetime.datetime(2020, 7, 24, 13, 41, 17, 787842)),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_begin',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 24, 13, 41, 17, 786139)),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_end',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 24, 13, 41, 17, 786174)),
        ),
    ]
