# Generated by Django 3.0.7 on 2020-07-24 13:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasktracker', '0020_auto_20200724_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('S', 'Simple'), ('T', 'Template'), ('D', 'Decomposite')], default='S', max_length=1),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='date_point',
            field=models.DateField(default=datetime.datetime(2020, 7, 24, 13, 51, 27, 281488)),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_begin',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 24, 13, 51, 27, 277844)),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_end',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 24, 13, 51, 27, 277899)),
        ),
    ]
