# Generated by Django 3.0.7 on 2020-07-24 14:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasktracker', '0021_auto_20200724_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistic',
            name='date_point',
            field=models.DateField(default=datetime.datetime(2020, 7, 24, 14, 2, 34, 555453)),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_begin',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 24, 14, 2, 34, 553529)),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_end',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 24, 14, 2, 34, 553559)),
        ),
    ]
