# Generated by Django 3.0.7 on 2020-08-08 12:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasktracker', '0022_auto_20200724_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistic',
            name='date_point',
            field=models.DateField(default=datetime.datetime(2020, 8, 8, 12, 33, 43, 510962)),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_begin',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 8, 12, 33, 43, 509384)),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_end',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 8, 12, 33, 43, 509426)),
        ),
    ]
