# Generated by Django 3.0.7 on 2020-08-20 21:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasktracker', '0023_auto_20200808_1233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='template_to',
        ),
        migrations.AddField(
            model_name='task',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templ', to='tasktracker.Template'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='date_point',
            field=models.DateField(default=datetime.datetime(2020, 8, 20, 21, 27, 37, 791270)),
        ),
        migrations.AlterField(
            model_name='task',
            name='decomposite_task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subtasks', to='tasktracker.Task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_begin',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 20, 21, 27, 37, 790672)),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_end',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 20, 21, 27, 37, 790708)),
        ),
    ]
